'use strict';const fs=require('fs'),create=require('../tools/route-harness');const out=[];
function fresh(li){const g=create();g.api.newGame();g.api.loadLevel(li);g.api.startLevel();return g;}
function run(g,input,n){for(let i=0;i<n;i++){g.route.input(input);g.route.step();}}
// Test sentinel traverse before first active charge, with a real-ground starting state.
for(const li of [4,6,7]){let g=fresh(li);let a=g.api;const e=a.ents.find(e=>e.t==='K'||e.t==='Y');const x=e.x;Object.assign(a.player,{x:x-65,y:142,onGround:true,jHeld:false});let trace=[];for(let f=0;f<100;f++){run(g,[1,1,0],1);if(f%5===0)trace.push({f,x:a.player.x,y:a.player.y,energy:a.player.energy,enemyState:e.state,enemyX:e.x});}out.push({type:'constant-jump-past-first-enemy',level:li+1,startX:x-65,trace});}
// Fixed-input completion checks, from phase checkpoint/approach, no altered enemy or physics.
for(const [li,part,period] of [[4,4,60],[4,5,60],[6,1,30],[6,3,30],[6,5,30],[7,1,30]]){let g=fresh(li);let a=g.api,z=a.L.zones.find(z=>z.part===part&&!z.transition);Object.assign(a.player,{x:z.x0+51,y:142,onGround:true,jHeld:false});let inputs=[],hits=[],firstKey=null,startKeys=a.player.keys;for(let f=0;f<1500&&a.state==='play';f++){const before=a.player.energy;run(g,[1,f%period<period-2,0],1);if(a.player.energy<before-2)hits.push(f);if(a.player.keys>startKeys&&firstKey===null)firstKey=f;inputs.push([1,f%period<period-2?1:0,0]);if(a.player.dead)break;if(a.player.x>z.x1+55)break;}out.push({type:'fixed-input',level:li+1,part,period,frames:inputs.length,state:a.state,firstKey,hits,player:{...a.player,mover:!!a.player.mover},check:{...a.check}});}
// Key persistence and opened-door persistence across death, with actual pickup and door contact.
for(let li=4;li<8;li++){let g=fresh(li),a=g.api;const k=a.items.find(i=>i.t==='k'),door=a.L.zones.find(z=>z.transition),c=door.x0/16+1;Object.assign(a.player,{x:k.x,y:k.y-6,onGround:false,jHeld:false});run(g,[0,0,0],1);const afterPickup=a.player.keys;a.player.energy=0;run(g,[0,0,0],92);const afterDeath=a.player.keys;Object.assign(a.player,{x:c*16-11,y:142,vx:0,vy:0,onGround:true});run(g,[1,0,0],20);a.player.energy=0;run(g,[0,0,0],92);out.push({type:'persistence',level:li+1,afterPickup,afterDeath,afterDoorDeathKeys:a.player.keys,door:[a.tileAt(c,8),a.tileAt(c,9)],keyExists:a.items.some(i=>i.t==='k'&&i.x===k.x)});}
// Crumble expiry and respawn reset; use real tile states and actual standing-trigger.
for(let li=5;li<8;li++){let g=fresh(li),a=g.api,cr=a.crumbles[0];Object.assign(a.player,{x:cr.x+3,y:cr.y-18,onGround:true,jHeld:false});let states=[];for(let f=0;f<80;f++){run(g,[0,0,0],1);if([0,59,60,61,79].includes(f))states.push({f,crState:cr.state,timer:cr.timer,y:a.player.y,dead:a.player.dead});}a.player.energy=0;run(g,[0,0,0],92);out.push({type:'crumble',level:li+1,states,afterRespawn:a.crumbles.filter(c=>c.state!=='solid').length});}
fs.writeFileSync(__dirname+'/targeted-results.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out.filter(o=>o.type!=='constant-jump-past-first-enemy'),null,2));
